### ISSUE TITLE
无限弹验证怎么搞啊

### ISSUE THREAD

**Issue by DoubleShift** [MeikleH/hema_delivery#1]
还说改一下丢服务器上去，就无限要滑一下，这ip就脏了啊

**Comment by DoubleShift** [comment]
亲，网络拥堵
请稍后重试

才几分钟，ip挂了

**Comment by MeikleH** [comment]
之前跑了几天都没出问题，但最近发现反爬越来越严了，除了用云然后动态换ip之外确实没啥好办法，或者可以选择多加几个商品轮流访问试试，要么就是把频率再降低一点。
